ai/urls.py
from django.urls import path 
from ai.views import *

urlpatterns = [
    # For Admin
    path('admin/crm/ai-assistant/', aiCategory, name='aiCategory'),
    path('admin/crm/ai-assistant/history/', aiHistory, name='aiHistory'),
    path('admin/crm/ai-assistant/delete/<int:id>/', aiHistoryDelete, name='aiHistoryDelete'),
    path('ai-assistant/content-generator/category/<str:category>/', openAiContentGeneration, name='openAiContentGeneration'),
    
    # For User
    path('user/dashboard/ai-assistant/', useraiCategory, name='useraiCategory'),
    path('user/dashboard/ai-assistant/history/', useraiHistory, name='useraiHistory'),
    path('user/dashboard/ai-assistant/delete/<int:id>/', useraiHistoryDelete, name='useraiHistoryDelete'),
    path('user/ai-assistant/content-generator/category/<str:category>/', useropenAiContentGeneration, name='useropenAiContentGeneration'),
]

core/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('oldadmin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name="crmHome"), name='admin_redirect'),
    path('admin/', RedirectView.as_view(pattern_name="crmHome"), name='admin_redirect'),
    path('crm/', RedirectView.as_view(pattern_name="crmHome"), name='admin_redirect'),
    path('dashboard/', RedirectView.as_view(pattern_name="userDashboard"), name='user_redirect'),
    path('user/', RedirectView.as_view(pattern_name="userDashboard"), name='user_redirect'),
    path('', include('adminapp.urls')),
    path('', include('userapp.urls')),
    path('', include('authapp.urls')),
    path('', include('legals.urls')),
    path('', include('crm.urls')),
    path('', include('reports.urls')),
    path('', include('marketing.urls')),
    path('', include('order.urls')),
    path('', include('ai.urls')),
    
]

handler404 = 'authapp.views.error_404'
handler404 = 'adminapp.views.error_404'
handler404 = 'crm.views.error_404'
handler404 = 'userapp.views.error_404'
handler404 = 'settings.views.error_404'
handler404 = 'legals.views.error_404'
handler404 = 'reports.views.error_404'
handler404 = 'marketing.views.error_404'
handler404 = 'order.views.error_404'
handler404 = 'ai.views.error_404'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   

crm/models.py
from django.db import models
from django.utils.text import slugify
from uuid import uuid4
from django.utils import timezone
from django.db.models import Sum
from authapp.models import *
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
import random
import string
from ckeditor.fields import RichTextField


# Product/Services
class items(models.Model):
    name = models.CharField(max_length=300)
    image = models.ImageField(upload_to='Product_Images/', blank=True, null=True)
    slug = models.SlugField(max_length=300, blank=True, null=True, unique=True)
    description = RichTextField()
    category = models.ForeignKey('itemCategory', on_delete=models.CASCADE)
    unit_type = models.CharField(max_length=100)
    rate = models.FloatField(null=True, blank=True)
    fake_sales = models.IntegerField(null=True, blank=True)
    fake_stars = models.IntegerField(null=True, blank=True)
    created_at = models.DateField(auto_now_add=True)
  
    
    def generate_unique_slug(self, base_slug):
        # Generate a random 3-character string
        random_chars = ''.join(random.choices(string.ascii_lowercase, k=3))
        return f"{base_slug}-{random_chars}"

    def save(self, *args, **kwargs):
        # Generate the initial slug from the item's name
        base_slug = slugify(self.name)
        slug = base_slug
        count = 1

        while items.objects.filter(slug=slug).exists():
            # Slug conflict exists, add an extra number to the slug
            slug = f"{base_slug}-{count}"
            count += 1

        self.slug = slug
        super().save(*args, **kwargs)
        
    def __str__(self):
        return self.name
    
# Product/Services Category   
class itemCategory(models.Model):
    name = models.CharField(max_length=300)
    slug = models.SlugField(max_length=300, blank=True, null=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.name

# CRM Projects
class crmProjects(models.Model):
    title = models.CharField(max_length=500)
    progress = models.IntegerField(blank=True, null=True, default=0)
    slug = models.SlugField(max_length=500, blank=True, null=True)
    PROJECT_TYPE_CHOICE = (
        ('client_project', 'Client Project'),
        ('internal_project', 'Internal Project'),
    )
    project_type = models.CharField(max_length=50, choices=PROJECT_TYPE_CHOICE, default='client_project')
    client = models.ForeignKey(Guser, on_delete=models.CASCADE, null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    start_date = models.DateField()
    deadline = models.DateField()
    price = models.IntegerField()
    team = models.ManyToManyField(User, related_name='project_team', blank=True)
    
    PROJECT_LABEL_CHOICE = (
        ('started', 'Started'),
        ('completed', 'Completed'),
        ('new_customer', 'New Customer'),
        ('important', 'Important'),
        ('closed', 'Closed'),
        ('running', 'Running'),
        ('canceled', 'Canceled'),
        ('pending', 'Pending'),
    )
    label = models.CharField(max_length=50, choices=PROJECT_LABEL_CHOICE, null=True, blank=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    
    def get_project_files(self):
        return ProjectFile.objects.filter(project=self)
    
    def __str__(self):
        return self.title

class ProjectFile(models.Model):
    project = models.ForeignKey(crmProjects, on_delete=models.CASCADE)
    upload_file = models.FileField(upload_to='project_files/')
    
# CRM Tasks
class crmTasks(models.Model):
    title = models.CharField(max_length=300)
    slug = models.SlugField(max_length=300, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    project = models.ForeignKey('crmProjects', on_delete=models.CASCADE)
    STATUS_CHOICES = (
        ('to_do', 'To do'),
        ('in_progress', 'In progress'),
        ('done', 'Done'),
    )
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='to_do')
    PRIORITY_CHOICES = (
        ('minor', 'Minor'),
        ('major', 'Major'),
        ('critical', 'Critical'),
        ('blocker', 'Blocker'),
    )
    priority = models.CharField(max_length=50, choices=PRIORITY_CHOICES, blank=True, null=True)
    PROJECT_LABEL_CHOICE = (
        ('started', 'Started'),
        ('completed', 'Completed'),
        ('new_customer', 'New Customer'),
        ('important', 'Important'),
        ('closed', 'Closed'),
        ('running', 'Running'),
        ('canceled', 'Canceled'),
        ('pending', 'Pending'),
    )
    label = models.CharField(max_length=50, choices=PROJECT_LABEL_CHOICE, null=True, blank=True)
    start_date = models.DateField(blank=True, null=True)
    deadline = models.DateField(blank=True, null=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

# CRM Invoice
class Invoice(models.Model):
    STATUS = [
    ('UNPAID', 'UNPAID'),
    ('PAID', 'PAID'),
    ]

    title = models.CharField(null=True, blank=True, max_length=100)
    number = models.CharField(null=True, blank=True, max_length=100)
    billDate = models.DateField(null=True, blank=True)
    dueDate = models.DateField(null=True, blank=True)
    status = models.CharField(choices=STATUS, default='UNPAID', max_length=100)
    discount_amount = models.FloatField(default=0)
    tax_amount = models.FloatField(default=0)
    other_fees_name = models.CharField(max_length=300, default="Other Fees", null=True, blank=True)
    other_fees_amount = models.FloatField(default=0)
    notes = models.TextField(null=True, blank=True, default='This is a computer generated invoice no need signature')

    #RELATED fields
    client = models.ForeignKey(Guser, blank=True, null=True, on_delete=models.SET_NULL)
    project = models.ForeignKey('crmProjects', null=True, on_delete=models.SET_NULL)
    products = models.ManyToManyField('items', related_name='invoice_related_items', blank=True)
    sub_total = models.FloatField(default=0.0, blank=True, null=True)

    #Utility fields
    uniqueId = models.CharField(null=True, blank=True, max_length=100)
    slug = models.SlugField(max_length=500, unique=True, blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    last_updated = models.DateTimeField(auto_now=True, blank=True, null=True)


    def __str__(self):
        if self.number:
            return self.number
        else:
            return "None"


    def save(self, *args, **kwargs):
        if self.number:
            self.slug = slugify(self.number)
        if self.uniqueId is None:
            self.uniqueId = str(uuid4()).split('-')[4]
        super().save(*args, **kwargs)
        
    def get_total(self):
        sub_total = self.sub_total or 0
        discount_amount = self.discount_amount or 0
        tax_amount = self.tax_amount or 0
        other_fees_amount = self.other_fees_amount or 0

        total = (sub_total + tax_amount + other_fees_amount) - discount_amount
        return total

    
    @classmethod
    def delete_blank_invoices(cls):
        two_hours_ago = timezone.now() - timezone.timedelta(hours=1)
        blank_invoices_to_delete = cls.objects.filter(
            products__isnull=True,
            date_created__lt=two_hours_ago
        )

        for invoice in blank_invoices_to_delete:
            invoice.delete()
        
    def get_status(self):
        # Check if the invoice is overdue based on the date
        if self.dueDate is not None and self.dueDate < timezone.now().date():
            if self.status != 'PAID':
                self.status = 'OVERDUE'

        # Set default values for sub_total, discount_amount, tax_amount, and other_fees_amount
        total_product_price = self.sub_total or 0
        discount_amount = self.discount_amount or 0
        tax_amount = self.tax_amount or 0
        other_fees_amount = self.other_fees_amount or 0

        # Calculate total after subtracting discount
        total_product_price -= discount_amount
        total_product_price += tax_amount + other_fees_amount

        total_payments = self.payments.aggregate(total=models.Sum('payment_ammount'))['total'] or 0

        # Calculate balance
        balance = total_product_price - total_payments

        if balance == 0 and total_product_price > 0:
            self.status = 'PAID'
        elif balance < 0:
            self.status = 'PAID'
        elif balance > 0:
            if self.dueDate is None or self.dueDate >= timezone.now().date():
                self.status = 'UNPAID'
            else:
                self.status = 'OVERDUE'

        self.save()

        return {"status": self.status, "balance": balance}

    
class InvoiceItem(models.Model):
    invoice = models.ForeignKey('Invoice', on_delete=models.CASCADE)
    item = models.ForeignKey('items', on_delete=models.CASCADE)
    unit_type = models.CharField(max_length=200, blank=True, null=True)
    quantity = models.IntegerField(default=1)
    unit_price = models.FloatField(default=0.0)
    sub_total = models.FloatField(default=0.0)

    def __str__(self):
        return f"{self.item.name} - Quantity: {self.quantity} - Invoice: #{self.invoice}"

   
# CRM Payments
class Payments(models.Model):
    invoice = models.ForeignKey('Invoice', blank=True, null=True, on_delete=models.SET_NULL, related_name='payments')
    title = models.CharField(max_length=200, blank=True, null=True)
    slug = models.SlugField(max_length=200, blank=True, null=True)
    payment_method = models.CharField(max_length=300, blank=True, null=True)
    payment_ammount = models.FloatField(blank=True, null=True)
    payment_date = models.DateField(blank=True, null=True)
    payment_note = models.TextField(blank=True, null=True)
    

templates/user/main/projects/projects.html
{% extends 'user/base.html' %}
{% load static %}
{% block title %}{{title}} - {{settings.name}}{% endblock title %}
{% block content %}
<style>
    .btn-group-sm>.btn-icon.btn, .btn-icon.btn-sm {
        font-size: 1.2rem !important;
        height: calc(1.625rem + 2px);
        width: calc(1.625rem + 2px);
    }
@media (min-width: 992px) {
  .card-datatable.table-responsive {
    overflow-x: hidden;
  }
}
</style>

    <!-- Content wrapper -->
    <div class="content-wrapper">

        <!-- Content -->
        <div class="container-xxl flex-grow-1 container-p-y">
            <div class="row align-items-center">
                <div class="col-md-6">
                    <h4 class="fw-bold py-3 mb-4">
                        <span class="text-muted fw-light">Dashboard /</span> Projects
                    </h4>
                </div>
            </div>
            <!--Table Card-->
            <div class="card">
                <div class="card-datatable table-responsive">
                  <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper dt-bootstrap5 no-footer">
                    <div class="card-header flex-column flex-md-row">
                      <div class="head-label">
                        <h5 class="card-title mb-0">All Projects</h5>
                      </div>
                      <div class="dt-action-buttons text-end pt-3 pt-md-0">
                      </div>
                    </div>
                    <!-- Your button -->
                    <div class="container mb-4">
                    <table class="datatables-basic table border-top dataTable no-footer dtr-column collapsed" id="DataTables_Table_0" aria-describedby="DataTables_Table_0_info">
                      <thead>
                        <tr>
                        <th style="width: 0px;" >#</th>
                        <th style="width: 130px;" >Title</th>
                        <th style="width: 150px;">Start Date</th>
                        <th style="width: 150px;">Deadline</th>
                        <th style="width: 180px;">Progress</th>
                        <th style="width: 130px;">Status</th>
                        <th style="width: 90px;" class="dtr-hidden">Price</th>
                        <th style="width: 0px;" class="sorting_disabled dtr-hidden">Actions</th>                           
                        </tr>
                      </thead>
                      <tbody>
                        {% for project in projects %}
                            <tr class="odd">
                                <td>{{ forloop.counter }}</td>
                                <td><span class="emp_name text-truncate"><a href="{% url 'userProjectDetail' slug=project.slug %}">{{ project.title }}</a></span></td>
                                <td>{{ project.start_date }}</td>
                                <td class="text-danger">{{ project.deadline }}</td>
                                <td>
                                  <div class="progress" role="progressbar" aria-label="Animated striped example" aria-valuenow="{{project.progress}}" aria-valuemin="0" aria-valuemax="100">
                                    <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: {{project.progress}}%">{{project.progress}}%</div>
                                  </div>
                                </td>
                                <td>{{ project.get_label_display }}</td>
                                <td>{{settings.currency_symbol}} {{ project.price }}</td>
                                <td class="dtr-hidden" style="">
                                    <a href="{% url 'userProjectDetail' slug=project.slug %}" class="btn btn-sm btn-icon item-edit">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
                                            <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
                                            <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
                                          </svg>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        <!-- ... more table rows ... -->
                      </tbody>
                      
                    </table>
                </div>
              </div> <!--Table Card-->         

          </div>
        <!-- / Content -->


    </div>
    <!-- Content wrapper -->
    <script>
        $(document).ready(function() {
            $('.table').DataTable({
                pageLength: 10, // Set the initial page length to 10
                lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "All"]], // Allow changing page length
                info: true, // Show the item count
                search: true // Enable search
            });
        });
    </script>
{% endblock content %}