ai/urls.py
from django.urls import path 
from ai.views import *

urlpatterns = [
    # For Admin
    path('admin/crm/ai-assistant/', aiCategory, name='aiCategory'),
    path('admin/crm/ai-assistant/history/', aiHistory, name='aiHistory'),
    path('admin/crm/ai-assistant/delete/<int:id>/', aiHistoryDelete, name='aiHistoryDelete'),
    path('ai-assistant/content-generator/category/<str:category>/', openAiContentGeneration, name='openAiContentGeneration'),
    
    # For User
    path('user/dashboard/ai-assistant/', useraiCategory, name='useraiCategory'),
    path('user/dashboard/ai-assistant/history/', useraiHistory, name='useraiHistory'),
    path('user/dashboard/ai-assistant/delete/<int:id>/', useraiHistoryDelete, name='useraiHistoryDelete'),
    path('user/ai-assistant/content-generator/category/<str:category>/', useropenAiContentGeneration, name='useropenAiContentGeneration'),
]

core/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('oldadmin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name="crmHome"), name='admin_redirect'),
    path('admin/', RedirectView.as_view(pattern_name="crmHome"), name='admin_redirect'),
    path('crm/', RedirectView.as_view(pattern_name="crmHome"), name='admin_redirect'),
    path('dashboard/', RedirectView.as_view(pattern_name="userDashboard"), name='user_redirect'),
    path('user/', RedirectView.as_view(pattern_name="userDashboard"), name='user_redirect'),
    path('', include('adminapp.urls')),
    path('', include('userapp.urls')),
    path('', include('authapp.urls')),
    path('', include('legals.urls')),
    path('', include('crm.urls')),
    path('', include('reports.urls')),
    path('', include('marketing.urls')),
    path('', include('order.urls')),
    path('', include('ai.urls')),
    
]

handler404 = 'authapp.views.error_404'
handler404 = 'adminapp.views.error_404'
handler404 = 'crm.views.error_404'
handler404 = 'userapp.views.error_404'
handler404 = 'settings.views.error_404'
handler404 = 'legals.views.error_404'
handler404 = 'reports.views.error_404'
handler404 = 'marketing.views.error_404'
handler404 = 'order.views.error_404'
handler404 = 'ai.views.error_404'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
   

crm/models.py
from django.db import models
from django.utils.text import slugify
from uuid import uuid4
from django.utils import timezone
from django.db.models import Sum
from authapp.models import *
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
import random
import string
from ckeditor.fields import RichTextField


# Product/Services
class items(models.Model):
    name = models.CharField(max_length=300)
    image = models.ImageField(upload_to='Product_Images/', blank=True, null=True)
    slug = models.SlugField(max_length=300, blank=True, null=True, unique=True)
    description = RichTextField()
    category = models.ForeignKey('itemCategory', on_delete=models.CASCADE)
    unit_type = models.CharField(max_length=100)
    rate = models.FloatField(null=True, blank=True)
    fake_sales = models.IntegerField(null=True, blank=True)
    fake_stars = models.IntegerField(null=True, blank=True)
    created_at = models.DateField(auto_now_add=True)
  
    
    def generate_unique_slug(self, base_slug):
        # Generate a random 3-character string
        random_chars = ''.join(random.choices(string.ascii_lowercase, k=3))
        return f"{base_slug}-{random_chars}"

    def save(self, *args, **kwargs):
        # Generate the initial slug from the item's name
        base_slug = slugify(self.name)
        slug = base_slug
        count = 1

        while items.objects.filter(slug=slug).exists():
            # Slug conflict exists, add an extra number to the slug
            slug = f"{base_slug}-{count}"
            count += 1

        self.slug = slug
        super().save(*args, **kwargs)
        
    def __str__(self):
        return self.name
    
# Product/Services Category   
class itemCategory(models.Model):
    name = models.CharField(max_length=300)
    slug = models.SlugField(max_length=300, blank=True, null=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.name

# CRM Projects
class crmProjects(models.Model):
    title = models.CharField(max_length=500)
    progress = models.IntegerField(blank=True, null=True, default=0)
    slug = models.SlugField(max_length=500, blank=True, null=True)
    PROJECT_TYPE_CHOICE = (
        ('client_project', 'Client Project'),
        ('internal_project', 'Internal Project'),
    )
    project_type = models.CharField(max_length=50, choices=PROJECT_TYPE_CHOICE, default='client_project')
    client = models.ForeignKey(Guser, on_delete=models.CASCADE, null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    start_date = models.DateField()
    deadline = models.DateField()
    price = models.IntegerField()
    team = models.ManyToManyField(User, related_name='project_team', blank=True)
    
    PROJECT_LABEL_CHOICE = (
        ('started', 'Started'),
        ('completed', 'Completed'),
        ('new_customer', 'New Customer'),
        ('important', 'Important'),
        ('closed', 'Closed'),
        ('running', 'Running'),
        ('canceled', 'Canceled'),
        ('pending', 'Pending'),
    )
    label = models.CharField(max_length=50, choices=PROJECT_LABEL_CHOICE, null=True, blank=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    
    def get_project_files(self):
        return ProjectFile.objects.filter(project=self)
    
    def __str__(self):
        return self.title

class ProjectFile(models.Model):
    project = models.ForeignKey(crmProjects, on_delete=models.CASCADE)
    upload_file = models.FileField(upload_to='project_files/')
    
# CRM Tasks
class crmTasks(models.Model):
    title = models.CharField(max_length=300)
    slug = models.SlugField(max_length=300, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    project = models.ForeignKey('crmProjects', on_delete=models.CASCADE)
    STATUS_CHOICES = (
        ('to_do', 'To do'),
        ('in_progress', 'In progress'),
        ('done', 'Done'),
    )
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='to_do')
    PRIORITY_CHOICES = (
        ('minor', 'Minor'),
        ('major', 'Major'),
        ('critical', 'Critical'),
        ('blocker', 'Blocker'),
    )
    priority = models.CharField(max_length=50, choices=PRIORITY_CHOICES, blank=True, null=True)
    PROJECT_LABEL_CHOICE = (
        ('started', 'Started'),
        ('completed', 'Completed'),
        ('new_customer', 'New Customer'),
        ('important', 'Important'),
        ('closed', 'Closed'),
        ('running', 'Running'),
        ('canceled', 'Canceled'),
        ('pending', 'Pending'),
    )
    label = models.CharField(max_length=50, choices=PROJECT_LABEL_CHOICE, null=True, blank=True)
    start_date = models.DateField(blank=True, null=True)
    deadline = models.DateField(blank=True, null=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

# CRM Invoice
class Invoice(models.Model):
    STATUS = [
    ('UNPAID', 'UNPAID'),
    ('PAID', 'PAID'),
    ]

    title = models.CharField(null=True, blank=True, max_length=100)
    number = models.CharField(null=True, blank=True, max_length=100)
    billDate = models.DateField(null=True, blank=True)
    dueDate = models.DateField(null=True, blank=True)
    status = models.CharField(choices=STATUS, default='UNPAID', max_length=100)
    discount_amount = models.FloatField(default=0)
    tax_amount = models.FloatField(default=0)
    other_fees_name = models.CharField(max_length=300, default="Other Fees", null=True, blank=True)
    other_fees_amount = models.FloatField(default=0)
    notes = models.TextField(null=True, blank=True, default='This is a computer generated invoice no need signature')

    #RELATED fields
    client = models.ForeignKey(Guser, blank=True, null=True, on_delete=models.SET_NULL)
    project = models.ForeignKey('crmProjects', null=True, on_delete=models.SET_NULL)
    products = models.ManyToManyField('items', related_name='invoice_related_items', blank=True)
    sub_total = models.FloatField(default=0.0, blank=True, null=True)

    #Utility fields
    uniqueId = models.CharField(null=True, blank=True, max_length=100)
    slug = models.SlugField(max_length=500, unique=True, blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    last_updated = models.DateTimeField(auto_now=True, blank=True, null=True)


    def __str__(self):
        if self.number:
            return self.number
        else:
            return "None"


    def save(self, *args, **kwargs):
        if self.number:
            self.slug = slugify(self.number)
        if self.uniqueId is None:
            self.uniqueId = str(uuid4()).split('-')[4]
        super().save(*args, **kwargs)
        
    def get_total(self):
        sub_total = self.sub_total or 0
        discount_amount = self.discount_amount or 0
        tax_amount = self.tax_amount or 0
        other_fees_amount = self.other_fees_amount or 0

        total = (sub_total + tax_amount + other_fees_amount) - discount_amount
        return total

    
    @classmethod
    def delete_blank_invoices(cls):
        two_hours_ago = timezone.now() - timezone.timedelta(hours=1)
        blank_invoices_to_delete = cls.objects.filter(
            products__isnull=True,
            date_created__lt=two_hours_ago
        )

        for invoice in blank_invoices_to_delete:
            invoice.delete()
        
    def get_status(self):
        # Check if the invoice is overdue based on the date
        if self.dueDate is not None and self.dueDate < timezone.now().date():
            if self.status != 'PAID':
                self.status = 'OVERDUE'

        # Set default values for sub_total, discount_amount, tax_amount, and other_fees_amount
        total_product_price = self.sub_total or 0
        discount_amount = self.discount_amount or 0
        tax_amount = self.tax_amount or 0
        other_fees_amount = self.other_fees_amount or 0

        # Calculate total after subtracting discount
        total_product_price -= discount_amount
        total_product_price += tax_amount + other_fees_amount

        total_payments = self.payments.aggregate(total=models.Sum('payment_ammount'))['total'] or 0

        # Calculate balance
        balance = total_product_price - total_payments

        if balance == 0 and total_product_price > 0:
            self.status = 'PAID'
        elif balance < 0:
            self.status = 'PAID'
        elif balance > 0:
            if self.dueDate is None or self.dueDate >= timezone.now().date():
                self.status = 'UNPAID'
            else:
                self.status = 'OVERDUE'

        self.save()

        return {"status": self.status, "balance": balance}

    
class InvoiceItem(models.Model):
    invoice = models.ForeignKey('Invoice', on_delete=models.CASCADE)
    item = models.ForeignKey('items', on_delete=models.CASCADE)
    unit_type = models.CharField(max_length=200, blank=True, null=True)
    quantity = models.IntegerField(default=1)
    unit_price = models.FloatField(default=0.0)
    sub_total = models.FloatField(default=0.0)

    def __str__(self):
        return f"{self.item.name} - Quantity: {self.quantity} - Invoice: #{self.invoice}"

   
# CRM Payments
class Payments(models.Model):
    invoice = models.ForeignKey('Invoice', blank=True, null=True, on_delete=models.SET_NULL, related_name='payments')
    title = models.CharField(max_length=200, blank=True, null=True)
    slug = models.SlugField(max_length=200, blank=True, null=True)
    payment_method = models.CharField(max_length=300, blank=True, null=True)
    payment_ammount = models.FloatField(blank=True, null=True)
    payment_date = models.DateField(blank=True, null=True)
    payment_note = models.TextField(blank=True, null=True)
    

templates/crm/main/ecom/partials/order-details.html
{% extends 'crm/base.html' %}
{% load static %}
{% block title %}Order #{{ order.order_id }} - {{ settings.name }}{% endblock title %}
{% block content %}
<style>
    .table-responsive::-webkit-scrollbar {
        height: 9px; 
    }

    .table-responsive::-webkit-scrollbar-thumb {
        background-color: #888;
        border-radius: 6px;
    }
</style>
<div class="container mt-3 mb-5">
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}
    <div class="row mb-5">
        <div class="col-md-8 mt-3">
            <div class="card mb-4">
                <div class="card-body">
                    <h4 class="card-title">Order Details</h4>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th style="min-width: 150px;">Order ID</th>
                                    <th style="min-width: 150px;">Total Amount</th>
                                    <th style="min-width: 150px;">Ordered At</th>
                                    <th style="min-width: 200px;">Paid By</th>
                                    {% if order.payment_method != 'offlinepayment' %}
                                        <th>Transaction ID</th>
                                    {% endif %}
                                    <th style="min-width: 150px;">Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>#{{ order.order_id }}</td>
                                    <td>{{ settings.currency_symbol }}{{ order.total_amount }}</td>
                                    <td>{{ order.ordered_at }}</td>
                                    <td>{{ order.get_payment_method_display }}</td>
                                    {% if order.payment_method != 'offlinepayment' %}
                                        <td>{{ order.transaction_id }}</td>
                                    {% endif %}
                                    <td>
                                        <span class="badge {% if order.status == 'pending' %}bg-warning{% elif order.status == 'confirmed' %}bg-primary{% elif order.status == 'completed' %}bg-success{% elif order.status == 'canceled' %}bg-danger{% endif %}">
                                            <b>{{ order.get_status_display }}</b>
                                        </span>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Ordered Items</h4>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Product</th>
                                    <th>Unit</th>
                                    <th>Unit Cost</th>
                                    <th>Quantity</th>
                                    <th>Subtotal</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for cart_item in cart_items %}
                                    <tr>
                                        <td><img style="width:80px; border-radius:5px;" src="{% if cart_item.product.image %}{{ cart_item.product.image.url }}{% else %}{% static 'crm/assets/img/placeholder.webp' %}{% endif %}" alt="" srcset=""></td>
                                        <td>{{ cart_item.product.name }}</td>
                                        <td>{{ cart_item.unit_type }}</td>
                                        <td>{{ settings.currency_symbol }}{{ cart_item.unit_price }}</td>
                                        <td>{{ cart_item.quantity }}</td>
                                        <td>{{ settings.currency_symbol }}{{ cart_item.subtotal }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4 mt-3">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Client Details</h4>
                    <dl class="row">
                        <dt class="col-sm-4">Name:</dt>
                        <dd class="col-sm-8">{{ order.user.userprofile.name }}</dd>

                        <dt class="col-sm-4">Email:</dt>
                        <dd class="col-sm-8">{{ order.user.userprofile.email }}</dd>

                        <dt class="col-sm-4">Phone:</dt>
                        <dd class="col-sm-8">{{ order.user.userprofile.phone }}</dd>

                        <dt class="col-sm-4">Address:</dt>
                        <dd class="col-sm-8">{{ order.user.userprofile.address }}</dd>

                        <dt class="col-sm-4">C - P, S:</dt>
                        <dd class="col-sm-8">{{ order.user.userprofile.city }} - {{ order.user.userprofile.zipcode }}, {{ order.user.userprofile.state }}</dd>

                        <dt class="col-sm-4">Country:</dt>
                        <dd class="col-sm-8">{{ order.user.userprofile.country }}</dd>
                    </dl>
                </div>
            </div>

            <div class="card mt-4">
                <div class="card-body">
                    <h4 class="card-title">Action</h4>
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.status }}
                        <button type="submit" class="btn btn-primary mt-3 w-100">Change Status</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}